### PR TITLE
Make sure robot made folders if there wasn't an existing one

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Comment by redbow-kimee** [comment]
what if one of the desired folders exists. but is a file.

**Comment by edf42001** [comment]
They aren't because they're folders?

**Comment by edf42001** [comment]
Like what do you mean? If the folders aren't on the robot already it creates them and if they are on the robot already then it doesn't.

**Comment by redbow-kimee** [comment]
if someone mistakenly creates a regular file (text or so) with the same name as one of the desired directories.

**Comment by edf42001** [comment]
Those would have an extension of some sort so it would not care. Also they won't.

**Review by cecer1712 — APPROVED** [review]
I can't see anything wrong with it currently, Kimee may disagree

**Comment by redbow-kimee** [comment]
The roboRIO has a UNIX based file system. "file extensions" are meaningless and not required.

That being said it is unlikely that someone create a file there.

**Review by redbow-kimee — APPROVED** [review]

**Pull request merged**
