### PR TITLE
Path drawer

### PR DESCRIPTION
**Pull request by edf42001**

### CODE REVIEW

**Review by redbow-kimee — CHANGES_REQUESTED** [review]
please remove the path files from this MR.

**Comment by edf42001** [comment]
No prob

**Comment by redbow-kimee** [comment]
the points array. can this be feet and inches

**Comment by edf42001** [comment]
It's for fine tuning the pixel locations of your path points, so it makes more sense to have it in pixels

**Comment by edf42001** [comment]
Oh or do you want an indicator of the points in feet and inches? yeah I think that already exists but is just hidden in the bottom right it could be moved.

**Review by redbow-kimee — APPROVED** [review]

**Review by cecer1712 — APPROVED** [review]

**Pull request merged**
