### PR TITLE
Arm

### PR DESCRIPTION
**Pull request by connor-marsh**
This was merged with the drive branch to test on everest. But this will probably cause merge conflicts with the drive publish global in the drive branch and we can help fix this down the road if you have problems with it, should be a simple fix.

### CODE REVIEW

**Comment by redbow-kimee** [comment]
explain the changes to the drive subsystem. in general MRs with changes to multiple subsystems or towards multiple features are subject to significant scrutiny and potential automatic rejection.

**Comment by edf42001** [comment]
We merged the drive branch into the elevator branch in order to get the change that was requested of the drive branch, which was adding the DistanceFromEnd control into Drive Published Globals so that the elevator could use that variable in a command that waits until the drivetrain is a certain distance from the end of the path and then raise the elevator. This is where the changes to the drive subsystem come from. However, we did this wrong by not pulling properly before merging so the change was not actually added. So then we made the change again on the elevator branch. This is an easy conflict to resolve. Simply merge one branch into the other and then make sure the effected VIs look good. This can be done with easy copy/pasting. We can do this now if you like, simply tell us if you'd like to merge the drive branch into master first, then we can merge that into the arm branch, or merge the arm branch first, and then we can merge that into the drive branch.

**Comment by edf42001** [comment]
I think the solution we would all be happy with is to go into this branch and copy the Drive folder from the most updated version of the drive branch into Arm. Then they are sure to be up to date.

**Comment by redbow-kimee** [comment]
Having multiple changes across multiple subsystems is not okay, it results in highly coupled code.. Each merge request should deal only with one subsystem. The ideal solution would be for the drive train to provide an API for the arm to consume. This would have to be split across two merge requests. one to provide a generalized API and one to consume said API.

**Comment by redbow-kimee** [comment]
I've sent my review to Bellini. He will review with @connor-marsh

**Review by cecer1712 — APPROVED** [review]

**Review by redbow-kimee — APPROVED** [review]

**Pull request merged**
